version: '3.3'

services:
  spark:
    build:
      context: .
    ports:
      - "8889:8888"  # IDE Jupyter (Alterando para 8889)
      - "4040:4040"  # Spark UI    (Após inicialização via IDE ou script)
      - "7077:7077"  # Spark API   (Acesso Externo)
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
      - ./config:/home/jovyan/.jupyter

    networks:
      - mybridge     # Nome da rede.

networks:
  mybridge:          # Nome da rede indicada no serviço.
    external:        # Indica que a rede é externa e já foi criada anteriormente.
      name: mybridge # Nome da rede externa que será usada.

volumes:
  notebooks:
  data:
  config:
