@startuml
title Evolução do Ecossistema Big Data

note as N2004
2004:
- Google publica paper MapReduce
- Google publica GFS (Google File System)
end note

note as N2006
2006:
- Doug Cutting cria Hadoop (MapReduce + HDFS)
end note

note as N2007
2007:
- Yahoo adota e impulsiona Hadoop
end note

note as N2008
2008:
- Hive (Facebook)
- Pig (Yahoo)
- HBase
end note

note as N2012
2012:
- Hadoop 2.0 introduz o YARN
end note

note as N2014
2014:
- Apache Spark (UC Berkeley)
end note

note as N2015
2015:
- Amazon S3 se consolida como Data Lake
end note

note as N2019
2019:
- Delta Lake (Databricks)
end note

note as N2020
2020:
- Apache Iceberg
- Apache Hudi
- Trino (ex-PrestoSQL)
end note

N2004 --> N2006
N2006 -> N2007
N2007 --> N2008
N2008 -> N2012
N2012 --> N2014
N2014 -> N2015
N2015 -> N2019
N2019 -> N2020
@enduml
