@startuml

skinparam backgroundColor #EEF9E3
skinparam package {
    BackgroundColor #D3D3D3
    BorderColor #A9A9A9
    FontColor #333333
    Shadowing false
}
skinparam class {
    BackgroundColor #F5F5F5
    BorderColor #A9A9A9
    FontColor #333333
    Shadowing false
}
skinparam note {
    BackgroundColor #B0C4DE
    BorderColor #A9A9A9
    FontColor #333333
    Shadowing false
}

package "Source Systems" {
    class "Oracle OLTP" {
        + "Transactional Data"
    }
}

package "Data Ingestion" {
    class "Apache NiFi" {
        + "Extract Data"
        + "Transform to Parquet"
        + "Load to HDFS"
    }
}

note "Data extraction\n and transformation" as NiFiNote
NiFiNote .. "Apache NiFi"

package "Storage" {
    class "HDFS" {
        + "Parquet Format"
    }
}

package "Data Orchestration" {
    class "Apache Airflow" {
        + "Schedule Tasks"
        + "Orchestrate Pipelines"
    }
}

note "Manage ETL\n workflows" as AirflowNote
AirflowNote .. "Apache Airflow"

package "Data Presentation" {
    class "Qlik" {
        + "Visualizations"
        + "Dashboards"
    }
}

"Oracle OLTP" --> "Apache NiFi" : Extracts Data
"Apache NiFi" --> "HDFS" : Loads Parquet
"Apache Airflow" --> "HDFS" : Orchestrates data jobs
"HDFS" --> "Qlik" : Data Consumption

@enduml
