{
 "title": "F1 Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=/public/img/andre/bandeira_corrida.jpg>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 },
   "options": {
    "content": "<h1><center>F1</center></h1>\r\n"
   }
  },
  {
   "title": "Circuito",
   "type": "table",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT r.name-- || ' - ' || r.date\r\n    FROM f1_schema.tb_laps_2022 f1\r\n    INNER JOIN f1_schema.dim_drivers d ON f1.\"driverId\" = d.\"driverId\"\r\n    INNER JOIN f1_schema.dim_races r ON f1.\"raceId\" = r.\"raceId\"\r\n    WHERE lap IN (SELECT max(lap) FROM f1_schema.tb_laps_2022 where \"raceId\" = (select max(\"raceId\") from f1_schema.tb_laps_2022 ))\r\n\tand r.\"raceId\" = (select max(\"raceId\") from f1_schema.tb_laps_2022 )\r\n  limit 1\r\n;"
    }
   ]
  },
  {
   "title": "Data",
   "type": "table",
   "gridPos": { "h": 3, "w": 13, "x": 11, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT r.date\r\n    FROM f1_schema.tb_laps_2022 f1\r\n    INNER JOIN f1_schema.dim_drivers d ON f1.\"driverId\" = d.\"driverId\"\r\n    INNER JOIN f1_schema.dim_races r ON f1.\"raceId\" = r.\"raceId\"\r\n    WHERE lap IN (SELECT max(lap) FROM f1_schema.tb_laps_2022 where \"raceId\" = (select max(\"raceId\") from f1_schema.tb_laps_2022 ))\r\n\tand r.\"raceId\" = (select max(\"raceId\") from f1_schema.tb_laps_2022 )\r\n  limit 1\r\n;"
    }
   ]
  },
  {
   "title": "Top 10 Positions",
   "type": "table",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT \r\n        --r.name AS circuit, \r\n        CONCAT(d.forename, ' ', d.surname) AS driver,\r\n        --f1.lap,\r\n        f1.position,\r\n\t\tf1.time AS lap_time\r\n\t\t--r.date\r\n    FROM f1_schema.tb_laps_2022 f1\r\n    INNER JOIN f1_schema.dim_drivers d ON f1.\"driverId\" = d.\"driverId\"\r\n    INNER JOIN f1_schema.dim_races r ON f1.\"raceId\" = r.\"raceId\"\r\n    WHERE lap IN (SELECT max(lap)-1 FROM f1_schema.tb_laps_2022 where \"raceId\" = (select max(\"raceId\") from f1_schema.tb_laps_2022 ))\r\n    AND position IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)\r\n\tand r.\"raceId\" = (select max(\"raceId\") from f1_schema.tb_laps_2022 )\r\n    ORDER BY position\r\n    LIMIT 10;"
    }
   ]
  },
  {
   "title": "Current Lap",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 4, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT max(lap)-1 FROM f1_schema.tb_laps_2022 where \"raceId\" = (select max(\"raceId\") from f1_schema.tb_laps_2022 );"
    }
   ]
  },
  {
   "title": "PODIUM",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 9 },
   "targets": [
    {
     "rawSql": "select \r\nTO_TIMESTAMP(x.dia_corrida || ' ' || x.hora_corrida, 'YYYY-MM-DD HH24:MI:SS')+ (x.tempo_acumulado * interval '1 s') as hora_final_da_volta,\r\nx.driver, \r\n--x.lap \r\nx.position\r\n\r\nfrom(\r\nSELECT\r\n    CONCAT(d.forename, ' ', d.surname) AS driver,\r\n\tf1.position,\r\n\tf1.lap as lap,\r\n\tr.date as dia_corrida,\r\n    r.time as hora_corrida,\r\n    sum(f1.milliseconds / 1000) OVER (PARTITION BY CONCAT(d.forename, ' ', d.surname) ORDER BY f1.lap) AS tempo_acumulado\r\nFROM\r\n\tf1_schema.tb_laps_2022 f1\r\n\tINNER JOIN f1_schema.dim_drivers d ON f1.\"driverId\" = d.\"driverId\"\r\n\tINNER JOIN f1_schema.dim_races r ON f1.\"raceId\" = r.\"raceId\"\r\n\tWHERE r.\"raceId\" = (select max(\"raceId\") from f1_schema.tb_laps_2022 )\r\n--\tAND position IN (1, 2, 3)\r\n--\tand f1.lap IN (SELECT max(lap) FROM f1_schema.tb_laps_2022 where \"raceId\" = (select max(\"raceId\") from f1_schema.tb_laps_2022 ))\r\nORDER BY\r\n    CONCAT(d.forename, ' ', d.surname),\r\n\tf1.lap,\r\n    r.time)x\r\nwhere \r\n--x.lap = (SELECT max(lap) FROM f1_schema.tb_laps_2022 where \"raceId\" = (select max(\"raceId\") from f1_schema.tb_laps_2022 ))\r\nx.driver in (SELECT \r\n        CONCAT(d.forename, ' ', d.surname) AS driver\r\n        FROM f1_schema.tb_laps_2022 f1\r\n    INNER JOIN f1_schema.dim_drivers d ON f1.\"driverId\" = d.\"driverId\"\r\n    INNER JOIN f1_schema.dim_races r ON f1.\"raceId\" = r.\"raceId\"\r\n    WHERE lap IN (SELECT max(lap) FROM f1_schema.tb_laps_2022 where \"raceId\" = (select max(\"raceId\") from f1_schema.tb_laps_2022 ))\r\n    AND position IN (2)\r\n\tand r.\"raceId\" = (select max(\"raceId\") from f1_schema.tb_laps_2022 )\r\n    ORDER BY position\r\n    LIMIT 3)\r\n\t;"
    },
    {
     "rawSql": "select \r\nTO_TIMESTAMP(x.dia_corrida || ' ' || x.hora_corrida, 'YYYY-MM-DD HH24:MI:SS')+ (x.tempo_acumulado * interval '1 s') as hora_final_da_volta,\r\nx.driver, \r\n--x.lap \r\nx.position\r\n\r\nfrom(\r\nSELECT\r\n    CONCAT(d.forename, ' ', d.surname) AS driver,\r\n\tf1.position,\r\n\tf1.lap as lap,\r\n\tr.date as dia_corrida,\r\n    r.time as hora_corrida,\r\n    sum(f1.milliseconds / 1000) OVER (PARTITION BY CONCAT(d.forename, ' ', d.surname) ORDER BY f1.lap) AS tempo_acumulado\r\nFROM\r\n\tf1_schema.tb_laps_2022 f1\r\n\tINNER JOIN f1_schema.dim_drivers d ON f1.\"driverId\" = d.\"driverId\"\r\n\tINNER JOIN f1_schema.dim_races r ON f1.\"raceId\" = r.\"raceId\"\r\n\tWHERE r.\"raceId\" = (select max(\"raceId\") from f1_schema.tb_laps_2022 )\r\n--\tAND position IN (1, 2, 3)\r\n--\tand f1.lap IN (SELECT max(lap) FROM f1_schema.tb_laps_2022 where \"raceId\" = (select max(\"raceId\") from f1_schema.tb_laps_2022 ))\r\nORDER BY\r\n    CONCAT(d.forename, ' ', d.surname),\r\n\tf1.lap,\r\n    r.time)x\r\nwhere \r\n--x.lap = (SELECT max(lap) FROM f1_schema.tb_laps_2022 where \"raceId\" = (select max(\"raceId\") from f1_schema.tb_laps_2022 ))\r\nx.driver in (SELECT \r\n        CONCAT(d.forename, ' ', d.surname) AS driver\r\n        FROM f1_schema.tb_laps_2022 f1\r\n    INNER JOIN f1_schema.dim_drivers d ON f1.\"driverId\" = d.\"driverId\"\r\n    INNER JOIN f1_schema.dim_races r ON f1.\"raceId\" = r.\"raceId\"\r\n    WHERE lap IN (SELECT max(lap) FROM f1_schema.tb_laps_2022 where \"raceId\" = (select max(\"raceId\") from f1_schema.tb_laps_2022 ))\r\n    AND position IN (1)\r\n\tand r.\"raceId\" = (select max(\"raceId\") from f1_schema.tb_laps_2022 )\r\n    ORDER BY position\r\n    LIMIT 3)\r\n\t;"
    },
    {
     "rawSql": "select \r\nTO_TIMESTAMP(x.dia_corrida || ' ' || x.hora_corrida, 'YYYY-MM-DD HH24:MI:SS')+ (x.tempo_acumulado * interval '1 s') as hora_final_da_volta,\r\nx.driver, \r\n--x.lap \r\nx.position\r\n\r\nfrom(\r\nSELECT\r\n    CONCAT(d.forename, ' ', d.surname) AS driver,\r\n\tf1.position,\r\n\tf1.lap as lap,\r\n\tr.date as dia_corrida,\r\n    r.time as hora_corrida,\r\n    sum(f1.milliseconds / 1000) OVER (PARTITION BY CONCAT(d.forename, ' ', d.surname) ORDER BY f1.lap) AS tempo_acumulado\r\nFROM\r\n\tf1_schema.tb_laps_2022 f1\r\n\tINNER JOIN f1_schema.dim_drivers d ON f1.\"driverId\" = d.\"driverId\"\r\n\tINNER JOIN f1_schema.dim_races r ON f1.\"raceId\" = r.\"raceId\"\r\n\tWHERE r.\"raceId\" = (select max(\"raceId\") from f1_schema.tb_laps_2022 )\r\n--\tAND position IN (1, 2, 3)\r\n--\tand f1.lap IN (SELECT max(lap) FROM f1_schema.tb_laps_2022 where \"raceId\" = (select max(\"raceId\") from f1_schema.tb_laps_2022 ))\r\nORDER BY\r\n    CONCAT(d.forename, ' ', d.surname),\r\n\tf1.lap,\r\n    r.time)x\r\nwhere \r\n--x.lap = (SELECT max(lap) FROM f1_schema.tb_laps_2022 where \"raceId\" = (select max(\"raceId\") from f1_schema.tb_laps_2022 ))\r\nx.driver in (SELECT \r\n        CONCAT(d.forename, ' ', d.surname) AS driver\r\n        FROM f1_schema.tb_laps_2022 f1\r\n    INNER JOIN f1_schema.dim_drivers d ON f1.\"driverId\" = d.\"driverId\"\r\n    INNER JOIN f1_schema.dim_races r ON f1.\"raceId\" = r.\"raceId\"\r\n    WHERE lap IN (SELECT max(lap) FROM f1_schema.tb_laps_2022 where \"raceId\" = (select max(\"raceId\") from f1_schema.tb_laps_2022 ))\r\n    AND position IN (3)\r\n\tand r.\"raceId\" = (select max(\"raceId\") from f1_schema.tb_laps_2022 )\r\n    ORDER BY position\r\n    LIMIT 3)\r\n\t;"
    }
   ]
  }
 ]
}